# .github/workflows/build_release.yml
name: Release appimage
on:
  workflow_run:
    workflows: ["Build packages"]
    types:
      - completed

jobs:
  run-after-a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODO Release"